name: Deploy VuePress
on: 
  push:
    branches:
      - 'vue-test-deploy'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
          ref: vue-test-deploy

    - name: Build and Deploy
      uses: jenkey2011/vuepress-deploy@dev
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: jenkey2011/vuepress-deploy-demo
        TARGET_BRANCH: gh_pages
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: docs/.vuepress/dist
